### ISSUE TITLE
How to activate on mac OS x?

### ISSUE THREAD

**Issue by Foadsf** [kankaristo/atom-multi-cursor-plus#11]
on mac when I press Alt+x I get ≈
How am I supposed to activate this plugging then?

**Comment by kankaristo** [comment]
Have you added the keybindings from [README.md](https://github.com/kankaristo/atom-multi-cursor-plus/blob/master/README.md#key-bindings)?

You can change `Alt+x` to something different, or use Atom's keybinding resolver (`Cmd+.` on macOS) to see if something else is handling the keybinding before it reaches multi-cursor-plus.

**Comment by ibyteyou** [comment]
+1
don't work "alt-up" and "alt-down" combinations. But eg package "multi-cursor" work excellent and my problem is not conflict this packages... i try disable and uninstall last.
Moreover all my osx friends can't enable this packages too.
If i can somehow help you - let give me test case.
MacOs Sierra 10.12.3. Atom 1.16.0 x64

**Comment by kankaristo** [comment]
Does Atom's keybinding resolver (`Cmd+.` on macOS) show something else handling the keybinding before it reaches multi-cursor-plus?

**Comment by ibyteyou** [comment]
Yea, it's conflict with emmet@2.4.3 default keybindings
<img width="684" alt="2017-05-02 15 00 45" src="https://cloud.githubusercontent.com/assets/16253399/25616955/5c7d2438-2f48-11e7-9094-0beaf8851789.png">
<img width="924" alt="2017-05-02 15 43 24" src="https://cloud.githubusercontent.com/assets/16253399/25618085/1f10c7e8-2f4e-11e7-98ca-198b12c2d04d.png">

**Comment by ibyteyou** [comment]
this example how work package "multi-cursor"

<img width="1038" alt="2017-05-02 15 05 36" src="https://cloud.githubusercontent.com/assets/16253399/25617050/f3ef8090-2f48-11e7-8b89-5b86c21c099d.png">

**Comment by kankaristo** [comment]
Try adding this to your `keymap.cson` before the multi-cursor-plus keybindings:
```cson
'atom-text-editor:not([mini])':
    # Unset emmet keybindings (conflict with multi-cursor-plus)
    'alt-up':   'unset!'
    'alt-down': 'unset!'
```

Does that fix it?

**Comment by ibyteyou** [comment]
no, it's uncomfortable.
i think that all (and i including), who turn to "multi-cursor-plus" after "multi-cursor" and failed, would like method "expand", i.e when e.g cursor move down and wait (if next action == up or down -> mark, else -> unmark)
it's reasonably?

p.s i want simple work how about "multi-cursor" `alt + down = Create cursor under`

**Comment by kankaristo** [comment]
I don't quite understand what you mean...

Did adding the above lines to your keymap fix it? Is adding them uncomfortable or did that fix it, but you feel that using `multi-cursor-plus` is uncomfortable?

If you want `alt+down` to create a cursor underneath, couldn't you use `multi-cursor` instead?

**Comment by ibyteyou** [comment]
The above line fix my problem, thx.
And i actually feel that using `multi-cursor-plus` is uncomfortable.
I can't use `multi-cursor`, because it does not allow me needful functional.
I'm trying use enabled `multi-cursor-plus` and `multi-cursor` together with successively set up `keymap.cson`, but it seemed to me ugly solution.
// I just suggested method "expand", to refuse `multi-cursor`

**Comment by kankaristo** [comment]
Ah, got it.

I still don't understand what your expand command would do, exactly?
- If `alt+down` adds a new cursor underneath, how would it be different from `multi-cursor`?
- Would I be able to skip a line (add cursors on lines 1 and 3, but not 2)?
- Would I be able to add multiple cursors on the same line?

Could you create a new issue, because this doesn't really seem to be related to this issue anymore?

I'll close this issue as solved.
