### ISSUE TITLE
Can't mark

### ISSUE THREAD

**Issue by akmur** [kankaristo/atom-multi-cursor-plus#5]
It seems like I'm not able to mark.

I tried to add a key binding, and also tried by using cmd+shift-p and select "multi-cursor-plus: mark" but it seems to me nothing happens. Am I doing something wrong?

**Comment by kankaristo** [comment]
Do the movement commands work?

Mark doesn't really have a good visual indication that something has happened, but moving the cursor away should leave a light blue (depending on your theme) cursor behind.

Note that you have to use the multi-cursor-plus movement commands. If you move the cursor with the regular movement commands (i.e. cursor keys or mouse), Atom takes over and combines the 2 cursors, because they're in the same position.

**Comment by kankaristo** [comment]
However, I haven't tested this at all on a Mac (I'm on Linux), but I don't think it should make a difference.

**Comment by akmur** [comment]
Thanks this is solved, it was caused by myself not understanding how to use the package, plus my keybindings were already used.
Thanks a lot
